# Generated by Django 4.2.3 on 2023-07-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('checkin', models.IntegerField()),
                ('checkout', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('roomtype', models.CharField(max_length=200)),
                ('identitytype', models.CharField(max_length=200)),
                ('identityproof', models.CharField(max_length=200)),
            ],
        ),
    ]
