# Generated by Django 4.2.3 on 2023-07-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='phone',
            new_name='mobile',
        ),
    ]
