# Generated by Django 4.2.3 on 2023-07-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanagement', '0002_rename_phone_people_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='checkin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='people',
            name='checkout',
            field=models.CharField(max_length=200),
        ),
    ]
