# Generated by Django 4.2.3 on 2023-07-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanagement', '0003_alter_people_checkin_alter_people_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='mobile',
            new_name='mbl',
        ),
    ]
