# Generated by Django 4.2.3 on 2023-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanagement', '0004_rename_mobile_people_mbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='guests',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='people',
            name='mbl',
            field=models.CharField(max_length=200),
        ),
    ]
